version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws sts get-caller-identity
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 242417635320.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t 242417635320.dkr.ecr.ap-south-1.amazonaws.com/devops-lab5-app:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - echo "Pushing Docker image..."
      - docker push 242417635320.dkr.ecr.ap-south-1.amazonaws.com/devops-lab5-app:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"lab5-app","imageUri":"242417635320.dkr.ecr.ap-south-1.amazonaws.com/devops-lab5-app:%s"}]' "$CODEBUILD_RESOLVED_SOURCE_VERSION" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
